version: "3.8"

services:
  tgbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tgbot-container
    environment:
      - TG_TOKEN=${TG_TOKEN:-default_token}
      - PASSWORD=${PASSWORD:-default_password}
      - WEB_EMAIL=${WEB_EMAIL:-default_email}
      - WEB_PASSWORD=${WEB_PASSWORD:-default_web_password}
    volumes:
      - ./cookies.pkl:/app/cookies.pkl
      - ./users.txt:/app/users.txt
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
    restart: unless-stopped 